name: relations
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pandas
  - tqdm
  - toml
  - seaborn
  - matplotlib
  - scikit-learn
  - seqeval
  - keras
  - tensorflow
  - networkx
  - nltk
  - pip:
    - transformers
