name = 'configuration for predefined region experiment'

[[data]]
name = 'nonhier+def'
train = 'data/full_data_EN.csv'
test = 'data/full_data_new_EN.csv'
hierarchical = ['DEFINIENDUM']
non-hierarchical = ['HAS_CAUSE', 'HAS_LOCATION', 'HAS_FORM', 'COMPOSITION_MEDIUM', 'HAS_FUNCTION', 'HAS_SIZE']

[[data]]
name = 'nonhier+def'
train = 'data/full_data_SL.csv'
test = 'data/full_data_new_SL.csv'
hierarchical = ['DEFINIENDUM']
non-hierarchical = ['HAS_CAUSE', 'HAS_LOCATION', 'HAS_FORM', 'COMPOSITION_MEDIUM', 'HAS_FUNCTION', 'HAS_SIZE']