name = 'train config for predefined region experiment'

[[train]]
experiment = 'EN_reg_nonhier+def'
model_id = 'bert-base-cased'
max_length = 128
batch_size = 4
epochs = 5

[[train]]
experiment = 'EN_reg_nonhier+def'
model_id = 'allenai/scibert_scivocab_cased'
max_length = 128
batch_size = 4
epochs = 5

[[train]]
experiment = 'SL_reg_nonhier+def'
model_id = 'bert-base-cased'
max_length = 128
batch_size = 4
epochs = 5

[[train]]
experiment = 'SL_reg_nonhier+def'
model_id = 'EMBEDDIA/crosloengual-bert'
max_length = 128
batch_size = 4
epochs = 5